data <- read.csv("messages.csv")
d <- head(sort(summary(data$tg_name), decreasing=TRUE), 10)
png(file = "pie.png")
pie(d, col=rainbow(length(d)), main="Топ 10 самых активных в ИС")
dev.off()
png(file = "abh.png")
h <- as.factor(format(as.POSIXct(data$dt, format="%Y-%m-%d %H:%M:%S"), format="%H"))
plot(h, col=rainbow(length(summary(h))), main="Активность по часам в ИС", xlab="время", ylab="количество вообщений")
dev.off()
png(file = "words.png")
boxplot(data$words, log="y", main="Распределение сообщений по количеству слов", ylab="количество слов")
dev.off()
png(file = "days.png")
d <- as.factor(format(as.POSIXct(data$dt, format="%Y-%m-%d %H:%M:%S"), format="%d"))
plot(d, col=rainbow(length(summary(d))), main="Активность по числам в ИС", xlab="число", ylab="количество вообщений")
dev.off()
